# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Users/brech/Desktop/EAGLE2_verilog/EAGLE2_freq_alg/drone/.Xil/Vivado-18600-LAPTOP-HDUT8SCT/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7z010clg400-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include c:/Users/brech/Desktop/EAGLE2_verilog/EAGLE2_freq_alg/src/bd/ipshared/ec67/hdl {
      C:/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      C:/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include c:/Users/brech/Desktop/EAGLE2_verilog/EAGLE2_freq_alg/src/bd/ipshared/ec67/hdl {
      c:/Users/brech/Desktop/EAGLE2_verilog/EAGLE2_freq_alg/src/bd/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_aw_atc.v
      c:/Users/brech/Desktop/EAGLE2_verilog/EAGLE2_freq_alg/src/bd/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_b_atc.v
      c:/Users/brech/Desktop/EAGLE2_verilog/EAGLE2_freq_alg/src/bd/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_w_atc.v
      c:/Users/brech/Desktop/EAGLE2_verilog/EAGLE2_freq_alg/src/bd/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_atc.v
      c:/Users/brech/Desktop/EAGLE2_verilog/EAGLE2_freq_alg/src/bd/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_trace_buffer.v
      c:/Users/brech/Desktop/EAGLE2_verilog/EAGLE2_freq_alg/src/bd/ip/drone_processing_system7_0_0/hdl/verilog/processing_system7_v5_5_processing_system7.v
      c:/Users/brech/Desktop/EAGLE2_verilog/EAGLE2_freq_alg/src/bd/ip/drone_processing_system7_0_0/synth/drone_processing_system7_0_0.v
      c:/Users/brech/Desktop/EAGLE2_verilog/EAGLE2_freq_alg/src/bd/ipshared/90cc/hdl/TDP_bram.v
      c:/Users/brech/Desktop/EAGLE2_verilog/EAGLE2_freq_alg/src/bd/ipshared/90cc/hdl/keccakF400Permutation.v
      c:/Users/brech/Desktop/EAGLE2_verilog/EAGLE2_freq_alg/src/bd/ipshared/90cc/hdl/EAGLE_interface_CONTROL.v
      c:/Users/brech/Desktop/EAGLE2_verilog/EAGLE2_freq_alg/src/bd/ipshared/90cc/hdl/EAGLE_to_AXI_interface.v
      c:/Users/brech/Desktop/EAGLE2_verilog/EAGLE2_freq_alg/src/bd/ipshared/90cc/hdl/crypto2020_hash_ip_v1_v1_0_S00_AXI.v
      c:/Users/brech/Desktop/EAGLE2_verilog/EAGLE2_freq_alg/src/bd/ipshared/90cc/hdl/crypto2020_hash_ip_v1_v1_0.v
      c:/Users/brech/Desktop/EAGLE2_verilog/EAGLE2_freq_alg/src/bd/ip/drone_crypto2020_hash_ip_v1_0_0/synth/drone_crypto2020_hash_ip_v1_0_0.v
      c:/Users/brech/Desktop/EAGLE2_verilog/EAGLE2_freq_alg/src/bd/ip/drone_xadc_wiz_0_0/drone_xadc_wiz_0_0.v
      c:/Users/brech/Desktop/EAGLE2_verilog/EAGLE2_freq_alg/src/bd/ipshared/4d9f/hdl/SWIPT_2020_v1_0_S00_AXI.v
      c:/Users/brech/Desktop/EAGLE2_verilog/EAGLE2_freq_alg/src/bd/ipshared/4d9f/swipt_toplevel.v
      c:/Users/brech/Desktop/EAGLE2_verilog/EAGLE2_freq_alg/src/bd/ipshared/4d9f/hdl/SWIPT_2020_v1_0.v
      c:/Users/brech/Desktop/EAGLE2_verilog/EAGLE2_freq_alg/src/bd/ip/drone_SWIPT_2020_0_0/synth/drone_SWIPT_2020_0_0.v
      c:/Users/brech/Desktop/EAGLE2_verilog/EAGLE2_freq_alg/src/bd/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v
      c:/Users/brech/Desktop/EAGLE2_verilog/EAGLE2_freq_alg/src/bd/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v
      c:/Users/brech/Desktop/EAGLE2_verilog/EAGLE2_freq_alg/src/bd/ipshared/2ef9/hdl/axi_register_slice_v2_1_vl_rfs.v
      c:/Users/brech/Desktop/EAGLE2_verilog/EAGLE2_freq_alg/src/bd/ipshared/47c9/hdl/axi_data_fifo_v2_1_vl_rfs.v
      c:/Users/brech/Desktop/EAGLE2_verilog/EAGLE2_freq_alg/src/bd/ipshared/b68e/hdl/axi_crossbar_v2_1_vl_rfs.v
      c:/Users/brech/Desktop/EAGLE2_verilog/EAGLE2_freq_alg/src/bd/ip/drone_xbar_0/synth/drone_xbar_0.v
      c:/Users/brech/Desktop/EAGLE2_verilog/EAGLE2_freq_alg/src/bd/ipshared/8dfa/hdl/axi_protocol_converter_v2_1_vl_rfs.v
      c:/Users/brech/Desktop/EAGLE2_verilog/EAGLE2_freq_alg/src/bd/ip/drone_auto_pc_9/synth/drone_auto_pc_9.v
      c:/Users/brech/Desktop/EAGLE2_verilog/EAGLE2_freq_alg/src/bd/ip/drone_auto_pc_0/synth/drone_auto_pc_0.v
      c:/Users/brech/Desktop/EAGLE2_verilog/EAGLE2_freq_alg/src/bd/ip/drone_auto_pc_1/synth/drone_auto_pc_1.v
      c:/Users/brech/Desktop/EAGLE2_verilog/EAGLE2_freq_alg/src/bd/ip/drone_auto_pc_2/synth/drone_auto_pc_2.v
      c:/Users/brech/Desktop/EAGLE2_verilog/EAGLE2_freq_alg/src/bd/ip/drone_auto_pc_3/synth/drone_auto_pc_3.v
      c:/Users/brech/Desktop/EAGLE2_verilog/EAGLE2_freq_alg/src/bd/ip/drone_auto_pc_4/synth/drone_auto_pc_4.v
      c:/Users/brech/Desktop/EAGLE2_verilog/EAGLE2_freq_alg/src/bd/ip/drone_auto_pc_5/synth/drone_auto_pc_5.v
      c:/Users/brech/Desktop/EAGLE2_verilog/EAGLE2_freq_alg/src/bd/ip/drone_auto_pc_6/synth/drone_auto_pc_6.v
      c:/Users/brech/Desktop/EAGLE2_verilog/EAGLE2_freq_alg/src/bd/ip/drone_auto_pc_7/synth/drone_auto_pc_7.v
      c:/Users/brech/Desktop/EAGLE2_verilog/EAGLE2_freq_alg/src/bd/ip/drone_auto_pc_8/synth/drone_auto_pc_8.v
      C:/Users/brech/Desktop/EAGLE2_verilog/EAGLE2_freq_alg/src/bd/synth/drone.v
      C:/Users/brech/Desktop/EAGLE2_verilog/EAGLE2_freq_alg/src/bd/hdl/drone_wrapper.v
      C:/Users/brech/Desktop/EAGLE2_v1/ZYBO/SwiptOut.v
      C:/Users/brech/Desktop/EAGLE2_v1/ZYBO/Freq.v
      C:/Users/brech/Desktop/EAGLE2_v1/ZYBO/Optimization.v
      C:/Users/brech/Desktop/EAGLE2_v1/ZYBO/DutyAdjust.v
      C:/Users/brech/Desktop/EAGLE2_v1/ZYBO/CalcL.v
    }
      rt::read_vhdl -lib xil_defaultlib {
      c:/Users/brech/Desktop/EAGLE2_verilog/EAGLE2_freq_alg/src/bd/ipshared/5f23/src/PWM_measure.vhd
      c:/Users/brech/Desktop/EAGLE2_verilog/EAGLE2_freq_alg/src/bd/ipshared/5f23/hdl/RC_v1_0_S00_AXI.vhd
      c:/Users/brech/Desktop/EAGLE2_verilog/EAGLE2_freq_alg/src/bd/ipshared/5f23/hdl/RC_v1_0.vhd
      c:/Users/brech/Desktop/EAGLE2_verilog/EAGLE2_freq_alg/src/bd/ip/drone_RC_1_0/synth/drone_RC_1_0.vhd
      c:/Users/brech/Desktop/EAGLE2_verilog/EAGLE2_freq_alg/src/bd/ip/drone_RC_0_0/synth/drone_RC_0_0.vhd
      c:/Users/brech/Desktop/EAGLE2_verilog/EAGLE2_freq_alg/src/bd/ip/drone_axi_gpio_testpins_0/synth/drone_axi_gpio_testpins_0.vhd
      c:/Users/brech/Desktop/EAGLE2_verilog/EAGLE2_freq_alg/src/bd/ip/drone_axi_gpio_led_0/synth/drone_axi_gpio_led_0.vhd
      c:/Users/brech/Desktop/EAGLE2_verilog/EAGLE2_freq_alg/src/bd/ipshared/7836/kill_switch.vhd
      c:/Users/brech/Desktop/EAGLE2_verilog/EAGLE2_freq_alg/src/bd/ip/drone_kill_switch_0_0/synth/drone_kill_switch_0_0.vhd
      c:/Users/brech/Desktop/EAGLE2_verilog/EAGLE2_freq_alg/src/bd/ipshared/7486/hdl/PWM_AXI.vhd
      c:/Users/brech/Desktop/EAGLE2_verilog/EAGLE2_freq_alg/src/bd/ipshared/7486/hdl/PWM_AXI_v1_0_S00_AXI.vhd
      c:/Users/brech/Desktop/EAGLE2_verilog/EAGLE2_freq_alg/src/bd/ipshared/7486/hdl/PWM_AXI_v1_0.vhd
      c:/Users/brech/Desktop/EAGLE2_verilog/EAGLE2_freq_alg/src/bd/ip/drone_PWM_AXI_triple_0_0/synth/drone_PWM_AXI_triple_0_0.vhd
      c:/Users/brech/Desktop/EAGLE2_verilog/EAGLE2_freq_alg/src/bd/ip/drone_PWM_AXI_triple_3_0/synth/drone_PWM_AXI_triple_3_0.vhd
      c:/Users/brech/Desktop/EAGLE2_verilog/EAGLE2_freq_alg/src/bd/ip/drone_PWM_AXI_triple_5_0/synth/drone_PWM_AXI_triple_5_0.vhd
      c:/Users/brech/Desktop/EAGLE2_verilog/EAGLE2_freq_alg/src/bd/ip/drone_rst_processing_system7_0_100M_0/synth/drone_rst_processing_system7_0_100M_0.vhd
      c:/Users/brech/Desktop/EAGLE2_verilog/EAGLE2_freq_alg/src/bd/ip/drone_PWM_AXI_triple_4_0/synth/drone_PWM_AXI_triple_4_0.vhd
    }
      rt::read_vhdl -lib axi_lite_ipif_v3_0_4 c:/Users/brech/Desktop/EAGLE2_verilog/EAGLE2_freq_alg/src/bd/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib lib_cdc_v1_0_2 c:/Users/brech/Desktop/EAGLE2_verilog/EAGLE2_freq_alg/src/bd/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd
      rt::read_vhdl -lib interrupt_control_v3_1_4 c:/Users/brech/Desktop/EAGLE2_verilog/EAGLE2_freq_alg/src/bd/ipshared/a040/hdl/interrupt_control_v3_1_vh_rfs.vhd
      rt::read_vhdl -lib axi_gpio_v2_0_23 c:/Users/brech/Desktop/EAGLE2_verilog/EAGLE2_freq_alg/src/bd/ipshared/bb35/hdl/axi_gpio_v2_0_vh_rfs.vhd
      rt::read_vhdl -lib proc_sys_reset_v5_0_13 c:/Users/brech/Desktop/EAGLE2_verilog/EAGLE2_freq_alg/src/bd/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd
      rt::read_vhdl -lib blk_mem_gen_v8_4_4 c:/Users/brech/Desktop/EAGLE2_verilog/EAGLE2_freq_alg/src/bd/ipshared/2985/hdl/blk_mem_gen_v8_4_vhsyn_rfs.vhd
      rt::read_vhdl -lib fifo_generator_v13_2_5 c:/Users/brech/Desktop/EAGLE2_verilog/EAGLE2_freq_alg/src/bd/ipshared/276e/hdl/fifo_generator_v13_2_vhsyn_rfs.vhd
      rt::read_vhdl -lib xpm C:/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top drone_wrapper
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "C:/Users/brech/Desktop/EAGLE2_verilog/EAGLE2_freq_alg/drone/.Xil/Vivado-18600-LAPTOP-HDUT8SCT/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
